# Generated by Django 5.2.7 on 2026-02-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('NAME', models.CharField(max_length=30)),
                ('ID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Birth_Date', models.DateField()),
                ('EMAIL', models.CharField(max_length=30)),
                ('PHONE', models.CharField(max_length=11)),
                ('ADDRESS', models.CharField(max_length=50)),
            ],
        ),
    ]
