# Generated by Django 5.2.7 on 2026-02-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ADDRESS',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='EMAIL',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='NAME',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='PHONE',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='ID',
            new_name='Serial',
        ),
    ]
