# Generated by Django 5.2.7 on 2026-02-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sheet', '0002_rename_address_student_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student Data'},
        ),
    ]
