# Generated by Django 5.2.7 on 2026-02-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sheet', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
